/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a docs page layout
 - create other pages (blog, faq, landing page, etc)
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/congratulations'],
    },
  ],
   */
};

module.exports = sidebars;
